
import { GameCard } from './types';

export const INITIAL_GAME_CARDS: GameCard[] = [
    { word: "bat", taboo: ["animal", "fly", "cave"], zh: "蝙蝠", img: "https://img.freepik.com/free-vector/cute-bat-background-with-branch_23-2147695866.jpg" }, 
    { word: "black cat", taboo: ["animal", "witch", "dog"], zh: "黑貓", img: "https://img.freepik.com/free-vector/halloween-cat-background-flat-design_23-2147914660.jpg" },
    { word: "blood", taboo: ["red", "vampire", "liquid", "vein"], zh: "血液", img: "https://img.freepik.com/free-vector/red-droplets-glyph-style_78370-4807.jpg" },
    { word: "broom", taboo: ["witch", "fly", "sweep", "brush"], zh: "掃帚", img: "https://img.freepik.com/free-psd/videogame-broom-icon-pack_23-2149840091.jpg" },
    { word: "candy", taboo: ["sweets", "chocolate", "trick-or-treat"], zh: "糖果", img: "https://img.freepik.com/free-vector/set-delicious-candies-flat-style_23-2147805095.jpg" },
    { word: "cauldron", taboo: ["witch", "pot", "potion", "poison"], zh: "魔力大釜", img: "https://img.freepik.com/free-vector/halloween-cauldron-with-eyeball-illustration-isolated_18591-83699.jpg" },
    { word: "cobweb", taboo: ["spider", "dusty", "dirty", "old"], zh: "蜘蛛網", img: "https://img.freepik.com/free-vector/hand-drawn-halloween-cobweb-collection_23-2148292376.jpg" },
    { word: "coffin", taboo: ["dead", "vampire", "box", "bury"], zh: "棺材", img: "https://img.freepik.com/free-vector/wooden-coffin-with-cross-symbol_1308-33188.jpg" },
    { word: "costume", taboo: ["clothes", "dress-up", "party"], zh: "服裝", img: "https://img.freepik.com/free-vector/collection-halloween-kids-characters_23-2147918671.jpg" },
    { word: "creepy", taboo: ["scary", "spooky", "spider", "weird"], zh: "令人毛骨悚然的", img: "https://img.freepik.com/free-photo/woman-posing-with-scary-bats_23-2147686955.jpg" },
    { word: "decoration", taboo: ["house", "party", "Halloween"], zh: "裝飾", img: "https://img.freepik.com/free-vector/big-decoration-design-kit_1117-237.jpg" },
    { word: "demon", taboo: ["evil", "devil", "bad", "spirit"], zh: "惡魔", img: "https://img.freepik.com/free-vector/oni-mask-with-sword-cartoon-icon-illustration-skull-mask-icon-concept-isolated-flat-cartoon-style_138676-2140.jpg" },
    { word: "Dracula", taboo: ["vampire", "fangs", "blood", "bat"], zh: "德古拉", img: "https://img.freepik.com/free-vector/flat-design-vampire-collection_23-2148279968.jpg" },
    { word: "fangs", taboo: ["teeth", "vampire", "sharp", "bite"], zh: "尖牙", img: "https://img.freepik.com/free-vector/vampire-teeth-realistic-composition-with-isolated-image-white-predators-teeth-with-fangs-transparent-background-vector-illustration_1284-73378.jpg" },
    { word: "fog", taboo: ["mist", "white", "weather", "see"], zh: "霧", img: "https://img.freepik.com/free-vector/realistic-dynamic-fog-background_23-2149111513.jpg" },
    { word: "Frankenstein", taboo: ["monster", "scientist", "green", "created"], zh: "科學怪人", img: "https://img.freepik.com/free-vector/cute-zombie-frankenstein-walking_138676-3070.jpg" },
    { word: "full moon", taboo: ["night", "sky", "werewolf", "sun"], zh: "滿月", img: "https://img.freepik.com/free-psd/realistic-planet-illustration_23-2151094981.jpg" },
    { word: "ghost", taboo: ["spirit", "white", "scary"], zh: "鬼魂", img: "https://img.freepik.com/free-vector/hand-drawn-flat-halloween-ghosts-collection_23-2149093983.jpg" },
    { word: "goblin", taboo: ["monster", "green", "small", "ugly"], zh: "哥布林", img: "https://img.freepik.com/free-vector/green-goblin-troll-cartoon-character-sticker_1308-65781.jpg" },
    { word: "graveyard", taboo: ["cemetery", "tombstone", "dead", "buried"], zh: "墓地", img: "https://img.freepik.com/free-vector/cemetery-gravestone-halloween-composition-ancient-cemetery-night-ghosts-float-graves-vector-illustration_1284-69554.jpg" },
    { word: "haunted house", taboo: ["scary", "ghost", "building"], zh: "鬼屋", img: "https://img.freepik.com/free-vector/flat-halloween-house-illustration_23-2149063972.jpg" },
    { word: "horror film", taboo: ["scary", "movie", "monster"], zh: "恐怖片", img: "https://img.freepik.com/free-vector/realistic-horror-movie-poster_23-2149650232.jpg" },
    { word: "jack o' lantern", taboo: ["pumpkin", "carve", "orange", "candle"], zh: "傑克南瓜燈", img: "https://img.freepik.com/free-photo/spooky-halloween-pumpkin-carving_23-2149495133.jpg" },
    { word: "lightning", taboo: ["storm", "sky", "thunder", "flash"], zh: "閃電", img: "https://img.freepik.com/free-vector/gold-lightning-icons-black-vector-illustration_1284-42968.jpg" },
    { word: "mask", taboo: ["costume", "face", "disguise"], zh: "面具", img: "https://img.freepik.com/free-photo/elegant-carnival-mask-with-glitter_23-2148401867.jpg" }, 
    { word: "monster", taboo: ["scary", "creature", "big", "ugly"], zh: "怪物", img: "https://img.freepik.com/free-vector/hand-drawn-bigfoot-sasquatch-yeti-adominable-snowman-illustration_23-2148846315.jpg" },
    { word: "mummy", taboo: ["bandages", "Egypt", "tomb", "dead"], zh: "木乃伊", img: "https://img.freepik.com/free-vector/cute-mummy-dabbing_138676-3064.jpg" },
    { word: "nightmare", taboo: ["dream", "scary", "sleep", "wake up"], zh: "噩夢", img: "https://img.freepik.com/free-vector/boy-having-nightmare_1308-22911.jpg" },
    { word: "owl", taboo: ["bird", "night", "fly", "hoot"], zh: "貓頭鷹", img: "https://img.freepik.com/free-vector/illustration-drawing-style-set-wildlife_53876-36868.jpg" },
    { word: "potion", taboo: ["witch", "magic", "cauldron", "drink"], zh: "藥水", img: "https://img.freepik.com/free-vector/gradient-love-potion-illustration_23-2149245991.jpg" },
    { word: "raven", taboo: ["bird", "black", "fly", "dark"], zh: "渡鴉", img: "https://img.freepik.com/free-vector/black-raven-isolated-white_225004-1262.jpg" }, 
    { word: "scarecrow", taboo: ["field", "birds", "straw", "hat"], zh: "稻草人", img: "https://img.freepik.com/free-vector/flat-illustration-autumn-celebration_23-2149595784.jpg" },
    { word: "scythe", taboo: ["grim reaper", "cut", "blade", "death"], zh: "鐮刀", img: "https://img.freepik.com/free-psd/3d-rendering-halloween-icon-design_23-2151791273.jpg" }, 
    { word: "scream", taboo: ["shout", "scared", "afraid", "loud"], zh: "尖叫", img: "https://img.freepik.com/free-photo/emotional-youngster-yells-loudly-opens-mouth-broadly-feels-desperate_273609-8949.jpg" },
    { word: "shadow", taboo: ["dark", "light", "shape", "follow"], zh: "影子", img: "https://img.freepik.com/free-photo/view-abstract-outdoors-daylight-shadows_23-2149080251.jpg" },
    { word: "skeleton", taboo: ["bones", "white", "body"], zh: "骷髏", img: "https://img.freepik.com/free-vector/hand-drawn-skeleton-cartoon-illustration_52683-122986.jpg" },
    { word: "skull", taboo: ["head", "bones", "dead", "skeleton"], zh: "骷髏頭", img: "https://img.freepik.com/free-vector/vintage-human-skull-concept_225004-1268.jpg" },
    { word: "spell", taboo: ["magic", "witch", "words", "book"], zh: "咒語", img: "https://img.freepik.com/free-vector/gypsy-fortune-teller-with-magic-crystal-ball-sitting-table-fortunetelling-card-candle-mystical-book-herb-potion-flask-object-set-isolated-white-background-palmistry-fate-prediction_575670-2121.jpg" },
    { word: "spider", taboo: ["legs", "eight", "web"], zh: "蜘蛛", img: "https://img.freepik.com/free-vector/hand-drawn-cartoon-spider-illustration_23-2150469210.jpg" },
    { word: "spooky", taboo: ["scary", "creepy", "ghost", "Halloween"], zh: "陰森的", img: "https://img.freepik.com/free-vector/crying-woman-being-scared-by-spooky-pumpkin_23-2149078502.jpg" },
    { word: "superstition", taboo: ["black cat", "lucky", "bad", "believe"], zh: "迷信", img: "https://img.freepik.com/free-vector/flat-friday-13th-background-with-black-cat_23-2149353469.jpg" },
    { word: "tombstone", taboo: ["graveyard", "dead", "stone", "grave"], zh: "墓碑", img: "https://img.freepik.com/free-vector/isolated-gravestone-white-background_1308-67454.jpg" },
    { word: "trick-or-treat", taboo: ["candy", "Halloween", "sweets"], zh: "不給糖就搗蛋", img: "https://img.freepik.com/free-photo/little-children-trick-treating-halloween_53876-41182.jpg" },
    { word: "wand", taboo: ["magic", "wizard", "stick", "spell"], zh: "魔杖", img: "https://img.freepik.com/free-photo/3d-wizard-hand-hold-magic-wand-with-golden-stars_107791-15402.jpg" },
    { word: "werewolf", taboo: ["full moon", "wolf", "transform", "hairy"], zh: "狼人", img: "https://img.freepik.com/free-vector/hand-drawn-werewolf-illustration_52683-96412.jpg" },
    { word: "witch", taboo: ["hat", "magic", "black cat"], zh: "女巫", img: "https://img.freepik.com/free-vector/little-witch-girl-flying-her-broom_52683-24649.jpg" },
    { word: "wizard", taboo: ["magic", "man", "wand", "hat"], zh: "巫師", img: "https://img.freepik.com/free-vector/hand-drawn-cartoon-wizard-illustration_23-2150986950.jpg" },
    { word: "zombie", taboo: ["dead", "brain", "walk"], zh: "殭屍", img: "https://img.freepik.com/free-vector/creepy-zombies-walking-white-background_1308-84307.jpg" }
];
